app = "bank-statements-web"
primary_region = "fra"

[build]
dockerfile = "Dockerfile"

[build.args]
VITE_API_URL = "https://bank-statements-api-test.fly.dev"

[env]

[http_service]
internal_port = 80
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 512
