name: Deploy Fly App
description: Launches (if needed), configures, and deploys a Fly.io app.

inputs:
  app_name:
    required: true
    description: Name of the Fly.io app
  region:
    required: false
    default: fra
    description: "Fly.io region (default: fra)"
  working_directory:
    required: true
    description: Directory where the Fly app lives (e.g., bank-statements-api)
  secrets:
    required: true
    description: Secrets to set in `key=value` newline-separated format

runs:
  using: "composite"
  steps:
    - run: .github/actions/deploy-fly-app/deploy.sh
      shell: bash
      env:
        FLY_APP_NAME: ${{ inputs.app_name }}
        FLY_REGION: ${{ inputs.region }}
        FLY_WORKING_DIR: ${{ inputs.working_directory }}
        FLY_SECRETS: |
          ${{ inputs.secrets }}
