"""normalise schema to models: status enum and unique indexes

Revision ID: b19fb1cb1c1c
Revises: b8w9x0y1z2a3
Create Date: 2026-06-28 13:53:45.171571

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b19fb1cb1c1c"
down_revision: Union[str, None] = "b8w9x0y1z2a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


jobstatus = sa.Enum("PENDING", "IN_PROGRESS", "COMPLETED", "FAILED", "CANCELLED", name="jobstatus")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    jobstatus.create(op.get_bind(), checkfirst=True)
    op.execute("ALTER TABLE background_jobs ALTER COLUMN status DROP DEFAULT")
    op.alter_column(
        "background_jobs",
        "status",
        existing_type=sa.VARCHAR(length=50),
        type_=jobstatus,
        existing_nullable=False,
        postgresql_using="status::jobstatus",
    )
    op.execute("ALTER TABLE background_jobs ALTER COLUMN status SET DEFAULT 'PENDING'")
    op.drop_constraint(op.f("refresh_tokens_token_hash_key"), "refresh_tokens", type_="unique")
    op.drop_index(op.f("ix_refresh_tokens_token_hash"), table_name="refresh_tokens")
    op.create_index(op.f("ix_refresh_tokens_token_hash"), "refresh_tokens", ["token_hash"], unique=True)
    op.drop_constraint(op.f("subscription_usage_subscription_id_key"), "subscription_usage", type_="unique")
    op.drop_index(op.f("ix_subscription_usage_subscription_id"), table_name="subscription_usage")
    op.create_index(op.f("ix_subscription_usage_subscription_id"), "subscription_usage", ["subscription_id"], unique=True)
    op.drop_constraint(op.f("subscriptions_user_id_key"), "subscriptions", type_="unique")
    op.drop_index(op.f("ix_subscriptions_user_id"), table_name="subscriptions")
    op.create_index(op.f("ix_subscriptions_user_id"), "subscriptions", ["user_id"], unique=True)
    op.drop_constraint(op.f("users_email_key"), "users", type_="unique")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_unique_constraint(op.f("users_email_key"), "users", ["email"], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f("ix_subscriptions_user_id"), table_name="subscriptions")
    op.create_index(op.f("ix_subscriptions_user_id"), "subscriptions", ["user_id"], unique=False)
    op.create_unique_constraint(
        op.f("subscriptions_user_id_key"), "subscriptions", ["user_id"], postgresql_nulls_not_distinct=False
    )
    op.drop_index(op.f("ix_subscription_usage_subscription_id"), table_name="subscription_usage")
    op.create_index(op.f("ix_subscription_usage_subscription_id"), "subscription_usage", ["subscription_id"], unique=False)
    op.create_unique_constraint(
        op.f("subscription_usage_subscription_id_key"),
        "subscription_usage",
        ["subscription_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(op.f("ix_refresh_tokens_token_hash"), table_name="refresh_tokens")
    op.create_index(op.f("ix_refresh_tokens_token_hash"), "refresh_tokens", ["token_hash"], unique=False)
    op.create_unique_constraint(
        op.f("refresh_tokens_token_hash_key"), "refresh_tokens", ["token_hash"], postgresql_nulls_not_distinct=False
    )
    op.execute("ALTER TABLE background_jobs ALTER COLUMN status DROP DEFAULT")
    op.alter_column(
        "background_jobs",
        "status",
        existing_type=jobstatus,
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
        postgresql_using="status::text",
    )
    op.execute("ALTER TABLE background_jobs ALTER COLUMN status SET DEFAULT 'PENDING'::character varying")
    jobstatus.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
