"""Add row_filters column to file_analysis_metadata

Revision ID: dc07aa0a9f15
Revises: 5bb67df27e64
Create Date: 2025-07-10 17:19:55.810076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "dc07aa0a9f15"
down_revision: Union[str, None] = "5bb67df27e64"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("file_analysis_metadata", sa.Column("row_filters", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("file_analysis_metadata", "row_filters")
    # ### end Alembic commands ###
