name: Create Neon Branch
description: Creates a temporary Neon branch and exports its ID and connection string.
inputs:
  neon_api_key:
    required: true
    description: Neon API key
  neon_project_id:
    required: true
    description: Neon project ID
  neon_template_branch_id:
    required: true
    description: Template branch ID
  neon_db_name:
    required: false
    description: Neon database name
  neon_db_username:
    required: false
    description: Neon database username
  neon_db_password:
    required: false
    description: Neon database password
outputs:
  branch_id:
    description: The created Neon branch ID
    value: ${{ steps.create_branch.outputs.branch_id }}
  db_url:
    description: The connection URI for the created branch
    value: ${{ steps.create_branch.outputs.db_url }}
runs:
  using: "composite"
  steps:
    - id: create_branch
      run: .github/actions/create-neon-branch/create.sh
      shell: bash
      env:
        NEON_API_KEY: ${{ inputs.neon_api_key }}
        NEON_PROJECT_ID: ${{ inputs.neon_project_id }}
        NEON_TEMPLATE_BRANCH_ID: ${{ inputs.neon_template_branch_id }}
        NEON_DB_NAME: ${{ inputs.neon_db_name }}
        NEON_DB_USERNAME: ${{ inputs.neon_db_username }}
        NEON_DB_PASSWORD: ${{ inputs.neon_db_password }}
        GITHUB_RUN_ID: ${{ github.run_id }}
        GITHUB_RUN_ATTEMPT: ${{ github.run_attempt }}
