services:
  test-db:
    image: postgres:17-alpine
    container_name: bank-statements-test-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bank_statements_test
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d bank_statements_test"]
      interval: 5s
      timeout: 5s
      retries: 5


