services:
  test-db:
    image: postgres:15
    container_name: bank-statements-test-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bank_statements_test
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bank_statements_test"]
      interval: 5s
      timeout: 5s
      retries: 5


