app = "bank-statements-api-test"
primary_region = "fra"

[build]
dockerfile = "Dockerfile"

[env]
PORT = "8000"
API_PORT = "8000"

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 512
