#!/bin/bash
REMOTE_SHA=$(git rev-parse @{upstream} 2>/dev/null || git rev-parse HEAD~1)

pnpm check

if git diff --name-only "$REMOTE_SHA" HEAD | grep -qE '\.(ts|tsx)$'; then
  pnpm test:web
fi

if git diff --name-only "$REMOTE_SHA" HEAD | grep -qE '\.py$'; then
  pnpm test:api
fi
