name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: ./bank-statements-api
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-interaction --no-root

      - name: Run tests
        working-directory: ./bank-statements-api
        run: |
          poetry run pytest

  test-frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pnpm
        run: npm install -g pnpm@8.15.9

      - name: Install dependencies
        working-directory: ./bank-statements-web
        run: |
          pnpm install --frozen-lockfile

      - name: Run tests
        working-directory: ./bank-statements-web
        run: |
          pnpm test
