name: Deploy Test Environment

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-backend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Create Neon Branch
        id: create-neon
        uses: ./.github/actions/create-neon-branch
        with:
          neon_api_key: ${{ secrets.NEON_API_KEY }}
          neon_project_id: ${{ secrets.NEON_PROJECT_ID }}
          neon_template_branch_id: ${{ secrets.NEON_TEMPLATE_BRANCH_ID }}
          neon_db_name: ${{ secrets.NEON_DB_NAME }}
          neon_db_username: ${{ secrets.NEON_DB_USERNAME }}
          neon_db_password: ${{ secrets.NEON_DB_PASSWORD }}

      - name: Deploy Backend to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        uses: ./.github/actions/deploy-fly-app
        with:
          app_name: bank-statements-api-test
          region: fra
          working_directory: bank-statements-api
          secrets: |
            DATABASE_URL=${{ steps.create-neon.outputs.db_url }}

  deploy-frontend-test:
    runs-on: ubuntu-latest
    needs: deploy-backend-test
    steps:
      - uses: actions/checkout@v3

      - name: Set up Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy Frontend to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        uses: ./.github/actions/deploy-fly-app
        with:
          app_name: bank-statements-web-test
          region: fra
          working_directory: bank-statements-web
          secrets: |
            VITE_API_URL=https://bank-statements-api-test.fly.dev
