name: Deploy Production Environment

on:
  workflow_run:
    workflows: ['Deploy Dev Environment']
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy-backend-prod:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
      - uses: actions/checkout@v3

      - name: Deploy Backend to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID_BACKEND: ${{ secrets.RENDER_SERVICE_ID_BACKEND }}
        run: |
          # Trigger a deploy on Render
          curl -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            "https://api.render.com/v1/services/$RENDER_SERVICE_ID_BACKEND/deploys"

  deploy-frontend-prod:
    runs-on: ubuntu-latest
    needs: deploy-backend-prod

    steps:
      - uses: actions/checkout@v3

      - name: Deploy Frontend to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID_FRONTEND: ${{ secrets.RENDER_SERVICE_ID_FRONTEND }}
        run: |
          # Trigger a deploy on Render
          curl -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            "https://api.render.com/v1/services/$RENDER_SERVICE_ID_FRONTEND/deploys"
